name: Deploy Flask Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Deploy Flask
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{qq secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🚀 Flask 앱 배포 시작"
            cd /stock4u/stock4u_backend_flask
            pip install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > flask.log 2>&1 &
            echo "✅ 배포 완료"